# -*- coding: utf-8 -*-
"""LV3_SecondTermProject_Malak_DECI4-S-418154

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nJBlmE96izscKF2IH7iZpjw7lyNGEOhz
"""

import pandas as pd
import requests

url = " https://api.github.com/search/repositories?q=machine+learning&sort=stars&order=desc&per_page=100"

response = requests.get(url)
data = response.json()

df = pd.DataFrame(data['items'])

selected_columns = ['name', 'owner', 'language', 'stargazers_count', 'forks_count', 'watchers_count', 'open_issues_count', 'created_at', 'updated_at', 'license']
df_selected = df[selected_columns].copy()

df_selected['owner'] = df_selected['owner'].apply(lambda x: x.get('login') if isinstance(x, dict) else None)

df_selected['license'] = df_selected['license'].apply(lambda x: x.get('name') if isinstance(x, dict) else None)

display(df_selected.head())

df_selected.info()

df_selected.columns

df_selected.shape

"""### Handle Missing Values

Let's check for any missing values in our `df_selected` DataFrame.
"""

display(df_selected.isnull().sum())

df_selected['language'] = df_selected['language'].fillna('Unknown')

df_selected['license'] = df_selected['license'].fillna('No License')

display(df_selected.isnull().sum())
display(df_selected.head())

"""### Handle Duplicate Records

Now, let's identify and remove any duplicate rows in our `df_selected` DataFrame. Duplicates can skew our analysis, so it's important to deal with them.
"""

duplicate_rows = df_selected.duplicated().sum()
print(f"Number of duplicate rows found: {duplicate_rows}")

import pandas as pd

df_selected['created_at'] = pd.to_datetime(df_selected['created_at'])
df_selected['updated_at'] = pd.to_datetime(df_selected['updated_at'])

df_selected = df_selected.rename(columns={
    'stargazers_count': 'stars',
    'forks_count': 'forks',
    'watchers_count': 'watchers',
    'open_issues_count': 'open_issues',
    'created_at': 'created_date',
    'updated_at': 'updated_date'
})

print(df_selected.info())
display(df_selected.head())

"""### Save and Verify the Dataset

The final step is to save the prepared dataset as: `github_projects.csv`

Saving the dataset creates a reusable local file that can be imported into SQLite during the next task.

After saving the file, we will reload it and check that it was stored correctly. This verification confirms that the dataset is complete, properly formatted, and ready for SQL analysis.
"""

df_selected.to_csv('github_projects.csv', index=False)

print("DataFrame saved as 'github_projects.csv'")

df_loaded = pd.read_csv('github_projects.csv')

df_loaded['created_date'] = pd.to_datetime(df_loaded['created_date'])
df_loaded['updated_date'] = pd.to_datetime(df_loaded['updated_date'])

print("DataFrame 'github_projects.csv' loaded successfully. Verifying info and head:")
print(df_loaded.info())
display(df_loaded.head())

"""### Create the SQLite Database

First, we'll load the `github_projects.csv` file and create a SQLite database. Then, we'll import the prepared dataset into a table named `Repositories`. Storing the data in a database allows us to retrieve and analyze repository information efficiently using SQL queries.
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')

df_repositories = pd.read_csv('github_projects.csv')

df_repositories['created_date'] = pd.to_datetime(df_repositories['created_date'])
df_repositories['updated_date'] = pd.to_datetime(df_repositories['updated_date'])

df_repositories['created_date'] = df_repositories['created_date'].dt.strftime('%Y-%m-%d %H:%M:%S')
df_repositories['updated_date'] = df_repositories['updated_date'].dt.strftime('%Y-%m-%d %H:%M:%S')

df_repositories.to_sql('Repositories', conn, if_exists='replace', index=False)

print("Dataset successfully imported into SQLite table 'Repositories'.")

query = "SELECT name, owner, language, stars, created_date FROM Repositories LIMIT 5"
df_from_sql = pd.read_sql_query(query, conn)

print("Verifying data loaded into 'Repositories' table:")
display(df_from_sql)

"""### Filtering and Searching Queries

Now, let's perform the required filtering and searching tasks on the `Repositories` table in our SQLite database.

#### Filter repositories with more than 10,000 stars
"""

query_high_stars = "SELECT name, owner, language, stars FROM Repositories WHERE stars > 10000 ORDER BY stars DESC"
df_high_stars = pd.read_sql_query(query_high_stars, conn)

print("Repositories with more than 10,000 stars:")
display(df_high_stars)

"""#### Find repositories whose names contain the word “Machine”"""

query_machine_name = "SELECT name, owner, language, stars FROM Repositories WHERE name LIKE '%Machine%' COLLATE NOCASE"
df_machine_name = pd.read_sql_query(query_machine_name, conn)

print("Repositories with 'Machine' in their name:")
display(df_machine_name)

"""### Logical Operators

Now, let's use logical operators (`AND`, `OR`, `NOT`) to create more specific SQL conditions and analyze our repository data.

#### Query using `AND`: Repositories with more than 50,000 stars and language is 'Python'
"""

query_and_operator = "SELECT name, owner, language, stars FROM Repositories WHERE stars > 50000 AND language = 'Python' ORDER BY stars DESC"
df_and_operator = pd.read_sql_query(query_and_operator, conn)

print("Repositories with >50,000 stars AND language 'Python':")
display(df_and_operator)

"""#### Query using `OR` and `NOT`: Repositories in 'C++' or 'Java', but not 'Unknown' language"""

query_or_not_operator = "SELECT name, owner, language, stars FROM Repositories WHERE (language = 'C++' OR language = 'Java') AND language != 'Unknown' ORDER BY stars DESC"
df_or_not_operator = pd.read_sql_query(query_or_not_operator, conn)

print("Repositories in 'C++' or 'Java' (excluding 'Unknown' language):")
display(df_or_not_operator)

"""### Sorting & Limiting Queries

Now, let's organize and rank the repositories based on their popularity by sorting them and limiting the results.

#### Display the Top 10 repositories with the highest number of stars
"""

query_top_10_stars = "SELECT name, owner, language, stars FROM Repositories ORDER BY stars DESC LIMIT 10"
df_top_10_stars = pd.read_sql_query(query_top_10_stars, conn)

print("Top 10 repositories with the highest number of stars:")
display(df_top_10_stars)

"""### Aggregate Functions

Now, let's calculate summary information about the repository dataset to get a general overview.

#### Count the total number of repositories
"""

query_total_repos = "SELECT COUNT(*) AS total_repositories FROM Repositories"
df_total_repos = pd.read_sql_query(query_total_repos, conn)

print("Total number of repositories:")
display(df_total_repos)

"""#### Calculate the average number of stars"""

query_avg_stars = "SELECT AVG(stars) AS average_stars FROM Repositories"
df_avg_stars = pd.read_sql_query(query_avg_stars, conn)

print("Average number of stars across all repositories:")
display(df_avg_stars)

"""### Grouping Analysis

After calculating the summary statistics, let's analyze the repositories based on their programming languages.

We will group repositories by programming language and display only those languages that contain more than 5 repositories. This analysis helps identify programming languages with a higher number of repositories.
"""

query_language_count = """SELECT language, COUNT(*) AS repository_count FROM Repositories GROUP BY language HAVING repository_count > 5 ORDER BY repository_count DESC"""
df_language_count = pd.read_sql_query(query_language_count, conn)

print("Programming languages with more than 5 repositories:")
display(df_language_count)

"""### Create Python Visualizations

Now that we've completed the SQL analysis, let's create visualizations using Matplotlib.

These visualizations will highlight the most popular repositories and show repository creation trends over time, making the results easier to understand by transforming numerical data into clear visual patterns.

#### Most Popular Repositories (Top 10 by Stars)
"""

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 7))
plt.barh(df_top_10_stars['name'], df_top_10_stars['stars'], color='skyblue')
plt.xlabel('Number of Stars')
plt.ylabel('Repository Name')
plt.title('Top 10 Repositories by Stars')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

"""#### Repository Creation Trends Over Time"""

df_selected['creation_year_month'] = df_selected['created_date'].dt.to_period('M')
creation_trends = df_selected.groupby('creation_year_month').size().reset_index(name='count')
creation_trends['creation_year_month'] = creation_trends['creation_year_month'].astype(str)

plt.figure(figsize=(14, 7))
plt.plot(creation_trends['creation_year_month'], creation_trends['count'], marker='o', linestyle='-', color='green')
plt.title('Repository Creation Trends Over Time')
plt.xlabel('Creation Year-Month')
plt.ylabel('Number of Repositories Created')
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

"""## Interpret Results

Based on the SQL queries and visualizations, here are some key insights from the GitHub repository data:

*   **Most Popular Repositories:** The 'Top 10 Repositories by Stars' visualization clearly shows that some machine learning repositories have a significantly higher number of stars, indicating extreme popularity. Several repositories have well over 100,000 stars, with `freeCodeCamp/freeCodeCamp` topping the list, followed by `jwasham/coding-interview-university` and `996icu/996.ICU`.

*   **Language Popularity:** When filtering for repositories with more than 50,000 stars, 'Python' is a prominent language, suggesting that many highly popular machine learning projects are developed in Python. The grouping analysis by `repository_count` further reveals that 'Python', 'JavaScript', 'TypeScript', and 'C++' are the most common languages among the top machine learning repositories, with Python having the highest count.

*   **Repository Creation Trends:** The 'Repository Creation Trends Over Time' visualization indicates a steady increase in the number of machine learning repositories created over the years, with a notable acceleration in recent years (though the data is limited to a specific range, usually for a few years).

*   **Overall Data Summary:** The dataset contains 100 repositories. The average number of stars is substantial, showing a general high interest in machine learning projects on GitHub. The `created_date` and `updated_date` fields, after conversion, show that the data covers repositories created and updated within a range, allowing for time-series analysis like the creation trends.

In summary, the analysis highlights the dominance of Python in the machine learning ecosystem, the high popularity of a few key repositories, and a continuous growth in the creation of machine learning projects over time.

# **Ethics Reflection**

### Question 1: Why is it important to verify data collected from public APIs?

**Answer:** It is crucial to verify data collected from public APIs for several reasons:

*   **Accuracy and Reliability:** Public APIs can sometimes provide outdated, incomplete, or incorrect data. Verification ensures that the data being used is accurate and reliable, which is fundamental for any credible analysis or decision-making.
*   **Data Integrity:** APIs might have rate limits, and errors in requests or responses can lead to corrupted or partially retrieved data. Verifying the data helps maintain its integrity.
*   **Bias Detection:** Data from public sources might unintentionally carry biases from its origin or collection methods. Verification steps can help identify and mitigate these biases before they influence analysis.
*   **Changing Data Structures:** APIs can change their data structures or return formats without extensive notice. Verification helps detect these changes and adapt the data processing accordingly.
*   **Security and Malice:** While less common with reputable public APIs, there's always a slight risk of malicious or compromised data. Verification adds a layer of scrutiny.

### Question 2: Why should data analysts document the source of their data?

**Answer:** Documenting data sources is a critical practice for data analysts due to the following:

*   **Reproducibility:** Clearly documented sources allow other analysts (or the analyst themselves in the future) to replicate the data collection process, ensuring that results can be verified and reproduced.
*   **Transparency and Trust:** Knowing the origin of the data builds trust in the analysis and its conclusions. Stakeholders can assess the credibility of the data if its source is transparently disclosed.
*   **Contextual Understanding:** Data doesn't exist in a vacuum. Knowing the source provides vital context about how the data was collected, its potential limitations, biases, and what it truly represents.
*   **Legal and Ethical Compliance:** Many industries have regulations regarding data provenance and usage. Documenting sources helps ensure compliance with legal and ethical standards, especially concerning privacy, intellectual property, and data ownership.
*   **Troubleshooting and Updates:** If an issue arises with the data, or if the data needs to be updated, knowing the exact source makes it much easier to trace, debug, or refresh the dataset.
*   **Attribution:** Giving credit to data providers is a matter of professional ethics and intellectual honesty.

### Question 3: How can missing or inaccurate data affect data analysis and decision-making?

**Answer:** Missing or inaccurate data can have severe detrimental effects on data analysis and decision-making:

*   **Skewed Results and Biased Conclusions:** Inaccurate data points or a significant amount of missing data can distort statistical analyses, leading to biased estimates, incorrect averages, and misleading trends. This can cause analysts to draw fundamentally wrong conclusions.
*   **Reduced Statistical Power:** Missing data reduces the effective sample size, which can decrease the statistical power of tests, making it harder to detect genuine relationships or effects.
*   **Flawed Models:** Machine learning models trained on inaccurate or incomplete data will likely perform poorly, making inaccurate predictions or classifications when deployed in real-world scenarios.
*   **Poor Business Decisions:** Decisions based on flawed analysis can lead to significant financial losses, misallocated resources, missed opportunities, and damage to reputation. For example, marketing campaigns based on inaccurate customer demographics could target the wrong audience.
*   **Loss of Credibility:** If an analysis is later found to be based on unreliable data, the credibility of the analyst and the organization can be severely undermined.
*   **Increased Time and Cost:** Dealing with missing or inaccurate data often requires extensive data cleaning, imputation, or re-collection efforts, which are time-consuming and costly.
*   **Ethical Implications:** Using unverified or flawed data, especially in sensitive areas like healthcare or finance, can lead to unfair or harmful outcomes for individuals or groups.
"""